const actions = {
  UPDATE_FIREBASE_USER: "UPDATE_FIREBASE_USER",
  GET_MONGO_USER: "GET_MONGO_USER",
  CREATE_USER: "CREATE_USER",
  LOGIN_USER: "LOGIN_USER",
  CREATE_NOTIFICATION: "CREATE_NOTIFICATION",
  DISMISS_NOTIFICATION: "DISMISS_NOTIFICATION",
  SET_LOADING: "SET_LOADING",
  SET_INITIAL_LOAD: "SET_INITIAL_LOAD",
  LOGOUT_USER: "LOGOUT_USER",
  WAIT_SINGLES_SUBMIT: "WAIT_SINGLES_SUBMIT",
  SUBMIT_SINGLES: "SUBMIT_SINGLES",
  SUBMIT_ALBUM: "SUBMIT_ALBUM",
  WAIT_ALBUM_SUBMIT: "WAIT_ALBUM_SUBMIT",
  FORM_LOADING: "FORM_LOADING",
  SEND_INVITE_EMAIL: "SEND_INVITE_EMAIL",
  RELOAD_USER: "RELOAD_USER",
  SET_USER_SINGLES: "SET_USER_SINGLES",
  SET_USER_ALBUMS: "SET_USER_ALBUMS",
};

export default actions;
